spring:
  application:
    name: library-book-service
book-rabbitmq:
  queues:
    exchange: book-direct-exchange
    createQueue: book-create-queue
    updateQueue: book-update-queue
    deleteQueue: book-delete-queue
  routes:
    createRoute: book-create-route
    updateRoute: book-update-route
    deleteRoute: book-delete-route
